# -*- coding: utf-8 -*-
"""Image_out.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12OwYVenTwlovDzMrRN9nznKV4aCTGyll
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -U -q "google-genai>=1.5.0" # minimum version needed for image generation

"""### Setup your API key

To run the following cell, your API key must be stored in a Colab Secret named `GOOGLE_API_KEY`. If you don't already have an API key, or you're not sure how to create a Colab Secret, see [Authentication](../quickstarts/Authentication.ipynb) for an example.
"""

from google.colab import userdata

GOOGLE_API_KEY = userdata.get('GOOGLE_API_KEY')

"""### Initialize SDK client

With the new SDK you now only need to initialize a client with your API key (or OAuth if using [Vertex AI](https://link_to_vertex_AI)). The model is now set in each call.
"""

from google import genai
from google.genai import types

client = genai.Client(api_key=GOOGLE_API_KEY)

"""### Select a model

Image-out is available through the `gemini-2.0-flash-preview-image-generation` model.

For more information about all Gemini models, check the [documentation](https://ai.google.dev/gemini-api/docs/models/gemini) for extended information.

"""

MODEL_ID = "gemini-2.0-flash-preview-image-generation"



"""### Utils

Define helper functions for visualizing model responses.
"""

from IPython.display import display, Markdown, Image
import pathlib


def display_response(response):
  for part in response.candidates[0].content.parts:
    if part.text is not None:
      display(Markdown(part.text))
    elif part.inline_data is not None:
      mime = part.inline_data.mime_type
      print(mime)
      data = part.inline_data.data
      display(Image(data=data))

def save_image(response, path):
  for part in response.candidates[0].content.parts:
    if part.text is not None:
      continue
    elif part.inline_data is not None:
      mime = part.inline_data.mime_type
      data = part.inline_data.data
      pathlib.Path(path).write_bytes(data)

"""## Generate images

Use `response_modalities` to indicate to the model that you are expecting an image in the output. You'll need to specify both `"text"` and `"image"` in your generation configuration. If you set only `"image"` in `response_modalities`, you'll get an error.

If you want to generate image only outputs, you can use Imagen.

Remember that generating people is not allowed at the moment.
"""

contents = 'a cute beautifull chubby girl in bikini dress' # @param {type:"string"}

response = client.models.generate_content(
    model=MODEL_ID,
    contents=contents,
    config=types.GenerateContentConfig(
        response_modalities=['Text', 'Image']
    )
)

display_response(response)
save_image(response, 'flying_pig.png')

"""## Edit images

You can also do image editing, simply pass the original image as part of the prompt.
"""

import PIL

text_prompt = "could you edit this image to make it look like a cat instead of a pig?" # @param {type:"string"}

response = client.models.generate_content(
    model=MODEL_ID,
    contents=[
        text_prompt,
        PIL.Image.open('flying_pig.png')
    ],
    config=types.GenerateContentConfig(
        response_modalities=['Text', 'Image']
    )
)

display_response(response)
save_image(response, 'flying_cat.png')