from typing import Dict, List, Any

SCHEMAS: Dict[str, Dict[str, Any]] = {
"companies":{"fields":{"_id":"id","clientName":"str","name":"str","contactPersonName":"str","subDomain":"str","primaryPhone":"str","secondaryPhone":"str","primaryEmail":"str","contactPersonEmail":"str","contactPersonPhone":"str","address":"str","country":"id","state":"id","city":"id","addOnServices":"array<enum:Sms|Email|IVR>","plan":"id","planStartDate":"datetime","planEndDate":"datetime","maxNoOfUsers":"int","maxNoOfProjects":"int","amountPaid":"number","totalGeneralExpenses":"number","allowPlanRenewalOnSamePrice":"bool","smartPingBalance":"int","status":"enum:Active|Archived","createdAt":"datetime"}},
"contracts":{"fields":{"_id":"id","amount":"number","anyReasonableExpenses":"number","chargesOnLatePayment":"number","company":"id","contractRate":"number","contractRateType":"enum:Hourly|Weekly","contractor":"id","startDate":"datetime","endDate":"datetime","generatedReferenceNo":"str","isSubContractAllowed":"bool","milestones":"array<object>","payForEachInvoiceDue":"bool","project":"id","scopeOfWork":"str","serviceTypes":"array<str>","status":"enum:Active|Archived","terminationPeriod":"number","witnesses":"array<object>"}},
"contractors":{"fields":{"_id":"id","company":"id","name":"str","countryCode":"str","phone":"str","email":"str","address":"str","country":"id","state":"id","city":"id","zipCode":"str","contractorType":"enum:Firm|Individual","contractorRateType":"enum:Hourly|Weekly","suitableFor":"enum:Residential|Commercial","isGoodsSupplier":"bool","yearsOfExperience":"int","status":"enum:Active|Inactive","createdAt":"datetime","updatedAt":"datetime"}},
"contract-payments":{"fields":{"_id":"id","company":"id","contractor":"id","project":"id","contract":"id","ordinal":"int","amount":"number","paymentStatus":"enum:Paid|Due","paymentMode":"enum:Cash|Cheque|Online","generatedReferenceNo":"str","referenceNo":"str","dueDate":"datetime","receivedOn":"datetime","status":"enum:Active|Archived","createdAt":"datetime","updatedAt":"datetime"}},
"brokers":{"fields":{"_id":"id","company":"id","name":"str","phone":"str","country":"id","city":"id","state":"id","address":"str","zipCode":"str","documentReferences":"array<object<title:str,referenceNo:str,_id:id>>","commissionPercent":"number","realEstateLicenseDetails":"object<licenseNo:str,licenseIssueDate:datetime,licenseExpirationDate:datetime>","yearStartedInRealEstate":"int","status":"enum:Active|Archived","createdAt":"datetime","updatedAt":"datetime"}},
"broker-payments":{"fields":{"_id":"id","company":"id","project":"id","property":"id","booking":"id","lead":"id","broker":"id","amount":"number","paymentStatus":"enum:Paid|Due","paymentMode":"enum:Cash|Online|Cheque","generatedReferenceNo":"str","paidOn":"datetime","status":"enum:Active|Archived","createdAt":"datetime","updatedAt":"datetime"}},
"cold-leads":{"fields":{"_id":"id","company":"id","countryCode":"str","phone":"str","coldLeadStatus":"enum:Pending|Converted","status":"enum:Active|Archived","createdAt":"datetime","updatedAt":"datetime"}},
"general-expenses":{"fields":{"_id":"id","company":"id","payeeName":"str","expenseType":"enum:Against Salary","amount":"number","taxes":"number","payableAmount":"number","paymentMode":"enum:Cash|Cheque|Online","generatedReferenceNo":"str","referenceNo":"str","dateOfPayment":"datetime","status":"enum:Active|Archived","createdAt":"datetime","updatedAt":"datetime"}},
"lands":{"fields":{"_id":"id","company":"id","name":"str","propertyType":"array<enum:Residential|Commercial>","address":"str","country":"id","state":"id","city":"id","zipCode":"str","location":"object","purchasePrice":"number","currentMarketValue":"number","isOnLease":"bool","rentalIncome":"number","occupancyStatus":"enum:Vacant|Occupied","nearByArea":"str","isAnyConstructionExists":"bool","plotSize":"number","sizeType":"enum:Square Meters|Hectares|Gaj|Square Feet|Square Yards|Acres","amenities":"array<id>","owners":"array<object>","status":"enum:Active|Inactive","createdAt":"datetime","updatedAt":"datetime"}},
"lead-assignments":{"fields":{"_id":"id","company":"id","lead":"id","team":"id","defaultPrimary":"id","defaultSecondary":"id","assignee":"id","status":"enum:Active|Archived","createdAt":"datetime","updatedAt":"datetime"}},
"lead-notes":{"fields":{"_id":"id","company":"id","lead":"id","communicationType":"enum:Call|In Person|WhatsApp","meetingDateTime":"datetime","siteVisitStatus":"enum:Pending|Scheduled|Visited","siteVisitScheduledDate":"datetime","nextSiteVisitScheduledDate":"datetime","status":"enum:Active|Archived","callDuration":"number","receiverPhone":"str","virtualPhone":"str","callDate":"datetime","createdAt":"datetime"}},
"lead-rotations":{"fields":{"_id":"id","company":"id","lead":"id","team":"id","assignee":"id","date":"datetime","createdAt":"datetime","updatedAt":"datetime"}},
"leads": {"fields": {"_id":"id","broker":"id","buyingTimeline":["0 TO 3 months","0 TO 6 months"],"commissionPercent":3,"company":"id","createdAt":["2025-03-31T06:55:42.351Z"],"email":["is@mail.com"],"leadStatus":["On going","Converted","Temporary Converted"],"maxBudget":1000,"minBudget":1000,"name":["Ishaan"],"phone":["9883726473"],"project":"id","propertyType":["Residential","Commercial"],"rotationCount":9,"secondaryPhone":["7689001334"],"sourceType":["Direct","Broker","Housing.com","99acres.com","MagicBricks.com"],"status": ["Active","Archived"],"updatedAt": ["2025-03-31T11:38:15.076Z"],"bhk":"id","bhkType":"id"}},
"lead-visited-properties":{"fields":{"_id":"id","company":"id","lead":"id","property":"id","status":"enum:Active|Archived","createdAt":"datetime","updatedAt":"datetime"}},
"plans":{"fields":{"_id":"id","name":"str","paymentDuration":"enum:Monthly|Quarterly|Yearly","price":"number","description":"str","features":"array<str>","maxNoOfUsers":"int","maxNoOfProjects":"int","status":"enum:Active|Archived","priceInUSD":"number"}},
"projects":{"fields":{"_id":"id","company":"id","land":"id","name":"str","projectType":"array<enum:Residential|Commercial>","projectUnitSubType":"array<id>","category":"id","projectStatus":"enum:Under construction","minBudget":"number","maxBudget":"number","startDate":"datetime","completionDate":"datetime","address":"str","country":"id","state":"id","city":"id","zipCode":"str","location":"object","reraRegistrationNumber":"str","projectRegistrationNumber":"str","isGovtApproved":"bool","govtApprovedDocuments":"array<str>","noOfUnitsResidential":"int","noOfBlocksResidential":"int","blocksResidential":"array<object>"}},
"properties":{"fields":{"_id":"id","company":"id","project":"id","propertyType":"enum:Residential|Commercial","propertyUnitSubType":"id","bhk":"id","bhkType":"id","blockName":"str","floorName":"str","series":"str","flatNo":"int","furnishedStatus":"enum:Furnished|Unfurnished|Semi-furnished","minBudget":"number","maxBudget":"number","facing":"enum:North|East|West|South","vastuCompliant":"bool","propertyArea":"number","carpetArea":"number","builtUpArea":"number","superBuiltUpArea":"number","propertyAreaType":"enum:Square Feet|Square Meters","noOfBalconies":"int","noOfBathRooms":"int","noOfBedRooms":"int","noOfKitchens":"int","noOfDrawingRooms":"int","noOfParkingLots":"int","propertyStatus":"enum:Available|Sold|Pending","status":"enum:Active|Archived","createdAt":"datetime","updatedAt":"datetime"}},
"property-bookings":{"fields":{"_id":"id","company":"id","lead":"id","project":"id","property":"id","bookingDate":"datetime","bookingType":"enum:Temporary Booking|Final Booking","saleablePrice":"number","basicPrice":"number","bookingAmount":"number","taxPercent":"number","taxAmount":"number","bookingPaymentStatus":"enum:Paid|Due|Refunded","paymentTerm":"enum:Loan|Without Loan","financeDeptStatus":"enum:Pending|Accepted|Rejected","extraCharges":"array<object<chargeFor:str,amount:number,_id:id>>","status":"enum:Active|Archived","createdAt":"datetime","updatedAt":"datetime"}},
"property-payments":{"fields":{"_id":"id","company":"id","project":"id","property":"id","booking":"id","paymentType":"enum:Booking Amount|CLP","transactionType":"enum:Credit|Debit","amount":"number","paymentStatus":"enum:Paid|Due","paymentMode":"enum:Cash|Cheque|Online","receivedOn":"datetime","generatedReferenceNo":"str","referenceNo":"str","dueFrom":"str","clpPhase":"str","ordinal":"int","status":"enum:Active|Archived","createdAt":"datetime","updatedAt":"datetime"}},
"rent-payments":{"fields":{"_id":"id","company":"id","project":"id","property":"id","tenant":"id","startDate":"datetime","endDate":"datetime","amount":"number","amountPaid":"number","paymentStatus":"enum:Paid|Due","paymentMode":"enum:Cash|Online|Cheque","generatedReferenceNo":"str","documentSerialNo":"str","paymentReceipt":"str","referenceNo":"str","receivedOn":"datetime","paymentInfo":"array<object>","partialPayments":"array<object>","status":"enum:Active|Archived","createdAt":"datetime","updatedAt":"datetime"}},
"tenants":{"fields":{"_id":"id","company":"id","project":"id","property":"id","name":"str","countryCode":"str","phone":"str","email":"str","totalMember":"int","members":"array<object<name:str,age:int,relation:str,_id:id>>","isPets":"bool","bookingDate":"datetime","bookingType":"enum:Temporary Booking|Final Booking","rentAmount":"number","rentIncrement":"number","depositAmount":"number","adjustedDepositAmount":"number","depositPaymentMode":"enum:Cash|Cheque|Online","depositReferenceNo":"str","isMaintenanceIncluded":"bool","isPoliceVerificationDone":"bool","rentStartDate":"datetime","rentAgreementStartDate":"datetime","dueRentAmount":"number","rentPaymentGeneratedOn":"datetime","tenantStatus":"enum:Left|Staying|Temporary Staying","status":"enum:Active|Archived","leavingDate":"datetime","createdAt":"datetime","updatedAt":"datetime"}},
"amenities":{"fields":{"_id":"id","name":"str","amenityType":"enum:Land|Project","status":"enum:Active|Archived","createdAt":"datetime","updatedAt":"datetime"}}

}
COLLECTIONS: List[str] = list(SCHEMAS.keys())
